apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-data
  namespace: webapp
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 1Gi